% --------- BASE DE CONHECIMENTO ---------

%% Pokemons ( nome, evolucao, bipede, inicial, lendario, pernas, voa, fossil)
pokemon('Bulbasaur', sim, não, sim, não, sim, não, não).
pokemon('Ivysaur', sim, não, não, não, sim, não, não).
pokemon('Venusaur', não, não, não, não, não, não, não).
pokemon('Charmander' , sim, sim, sim, não, sim, não, não).
pokemon('Charmeleon', sim, sim, não, não, sim, não, não).
pokemon('Charizard', não, sim, não, não, sim, sim, não).
pokemon('Squirtle', sim, sim, sim, não, sim, não, não).
pokemon('Watortle', sim, sim, sim, não, sim, não, não).
pokemon('Blastoise', não, sim, sim, não, sim, não, não).
pokemon('Caterpie', sim, não, não, não, sim, não, não).
pokemon('Metapod', sim, não, não, não, sim, não, não).
pokemon('Butterfree', não, sim, não, não, sim, sim, não).
pokemon('Weedle', sim, não, não, não, sim, não, não).
pokemon('Kakuna', sim, não, não, não, sim, não, não).
pokemon('Beedril', não, sim, não, não, sim, sim, não).
pokemon('Pidgey', sim, sim, não, não, sim, sim, não).
pokemon('Pidgeotto', sim, sim, não, não, sim, sim, não).
pokemon('Pidgeot', não, sim, não, não, sim, sim, não).
pokemon('Ratatta', sim, não, não, não, sim, não, não).
pokemon('Raticate', não, sim, não, não, sim, não, não).
pokemon('Spearow', sim, sim, não, não, sim, sim, não).
pokemon('Fearow', não, sim, não, não, sim, sim, não).
pokemon('Ekans', sim, não, não, não, não, não, não).
pokemon('Arbok', não, não, não, não, não, não, não).
pokemon('Pikachu', sim, sim, não, não, sim, não, não).
pokemon('Raichu', não, sim, não, não, sim, não, não).
pokemon('Sandshrew', sim, sim, não, não, sim, não, não).
pokemon('Sandslash', não, sim, não, não, sim, não, não).
pokemon('Nidoran F', sim, não, não, não, sim, não, não).
pokemon('Nidorina', sim, não, não, não, sim, não, não).
pokemon('Nidoqueen', não, sim, não, não, sim, não, não).
pokemon('Nidoran M', sim, não, não, não, sim, não, não).
pokemon('Nidorino', sim, não, não, não, sim, não, não).
pokemon('Nidoking', não, sim, não, não, sim, não, não).
pokemon('Clefairy', sim, sim, não, não, sim, não, não).
pokemon('Clefable', não, sim, não, não, sim, não, não).
pokemon('Vulpix', sim, não, não, não, sim, não, não).
pokemon('Ninetales', não, não, não, não, sim, não, não).
pokemon('Jigglypuff', sim, sim, não, não, sim, não, não).
pokemon('Wigglytuff', não, sim, não, não, sim, não, não).
pokemon('Zubat', sim, não, não, não, não, sim, não).
pokemon('Golbat', não, sim, não, não, sim, sim, não).
pokemon('Oddish', sim, sim, não, não, sim, não, não).
pokemon('Gloom', sim, sim, não, não, sim, não, não).
pokemon('Vileplume', não, sim, não, não, sim, não, não).
pokemon('Paras', sim, não, não, não, sim, não, não).
pokemon('Parasect', não, não, não, não, sim, não, não).
pokemon('Venonat', sim, sim, não, não, sim, não, não).
pokemon('Venomoth', não, não, não, não, sim, sim, não).
pokemon('Diglett', sim, não, não, não, não, não, não).
pokemon('Dugtrio', não, não, não, não, não, não, não).
pokemon('Meowth', sim, não, não, não, sim, não, não).
pokemon('Persian', não, não, não, não, sim, não, não).
pokemon('Psyduck', sim, sim, não, não, sim, não, não).
pokemon('Golduck', não, sim, não, não, sim, não, não).
pokemon('Mankey', sim, sim, não, não, sim, não, não).
pokemon('Primeape', não, sim, não, não, sim, não, não).
pokemon('Growlithe', sim, não, não, não, sim, não, não).
pokemon('Arcanine', não, não, não, não, sim, não, não).
pokemon('Poliwag', sim, sim, não, não, sim, não, não).
pokemon('Poliwhirl', sim, sim, não, não, sim, não, não).
pokemon('Poliwrath', não, sim, não, não, sim, não, não).
pokemon('Abra', sim, sim, não, não, sim, sim, não).
pokemon('Kadabra', sim, sim, não, não, sim, sim, não).
pokemon('Alakazan', não, sim, não, não, sim, sim, não).
pokemon('Machop', sim, sim, não, não, sim, não, não).
pokemon('Machoke', sim, sim, não, não, sim, não, não).
pokemon('Machamp', não, sim, não, não, sim, não, não).
pokemon('Bellsprout', sim, sim, não, não, sim, não, não).
pokemon('Weepinbell', sim, não, não, não, sim, sim, não).
pokemon('Victreebell', não, não, não, não, sim, sim, não).
pokemon('Tentacool', sim, não, não, não, sim, não, não).
pokemon('Tentacruel', não, não, não, não, sim, não, não).
pokemon('Geodude', sim, não, não, não, sim, sim, não).
pokemon('Graveler', sim, sim, não, não, sim, não, não).
pokemon('Golem', não, sim, não, não, sim, não, não).
pokemon('Ponyta', sim, não, não, não, sim, não, não).
pokemon('Rapidash', não, não, não, não, sim, não, não).
pokemon('Slowpoke', sim, não, não, não, sim, não, não).
pokemon('Slowbro', não, sim, não, não, sim, não, não).
pokemon('Magnemite', sim, não, não, não, não, sim, não).
pokemon('Magneton', não, não, não, não, não, sim, não).
pokemon('Farfetch''d', não, sim, não, não, sim, sim, não).
pokemon('Doduo', sim, sim, não, não, sim, não, não).
pokemon('Dodrio', não, sim, não, não, sim, não, não).
pokemon('Seel', sim, não, não, não, não, não, não).
pokemon('Dewgong', não, não, não, não, não, não, não).
pokemon('Grimer', sim, não, não, não, não, não, não).
pokemon('Muk', não, não, não, não, não, não, não).
pokemon('Shellder', sim, não, não, não, não, não, não).
pokemon('Cloyster', não, não, não, não, não, não, não).
pokemon('Gastly', sim, não, não, não, não, sim, não).
pokemon('Haunter', sim, não, não, não, não, sim, não).
pokemon('Gengar', não, sim, não, não, sim, sim, não).
pokemon('Onix', não, não, não, não, não, não, não).
pokemon('Drowzee', sim, sim, não, não, sim, não, não).
pokemon('Hypno', não, sim, não, não, sim, não, não).
pokemon('Krabby', sim, não, não, não, sim, não, não).
pokemon('Kingler', não, não, não, não, sim, não, não).
pokemon('Voltorb', sim, não, não, não, não, não, não).
pokemon('Electrode', não, não, não, não, não, não, não).
pokemon('Exeggcute', sim, não, não, não, não, não, não).
pokemon('Exeggutor', não, sim, não, não, sim, não, não).
pokemon('Cubone', sim, sim, não, não, sim, não, não).
pokemon('Marowak', não, sim, não, não, sim, não, não).
pokemon('Hitmonlee', não, sim, não, não, sim, não, não).
pokemon('Hitmonchan', não, sim, não, não, sim, não, não).
pokemon('Lickitung', não, sim, não, não, sim, não, não).
pokemon('Koffing', sim, não, não, não, não, sim, não).
pokemon('Weezing', não, não, não, não, não, sim, não).
pokemon('Rhyhorn', sim, não, não, não, sim, não, não).
pokemon('Rhydon', não, sim, não, não, sim, não, não).
pokemon('Chansey', não, sim, não, não, sim, não, não).
pokemon('Tangela', não, sim, não, não, sim, não, não).
pokemon('Kangaskhan', não, sim, não, não, sim, não, não).
pokemon('Horsea', sim, não, não, não, não, não, não).
pokemon('Seadra', não, não, não, não, não, não, não).
pokemon('Goldeen', sim, não, não, não, não, não, não).
pokemon('Seaking', não, não, não, não, não, não, não).
pokemon('Staryu', sim, sim, não, não, sim, não, não).
pokemon('Starmie', não, sim, não, não, sim, não, não).
pokemon('Mr.Mime', não, sim, não, não, sim, não, não).
pokemon('Scyther', não, sim, não, não, sim, sim, não).
pokemon('Jynx', não, não, não, não, não, não, não).
pokemon('Electabuzz', não, sim, não, não, sim, não, não).
pokemon('Magmar', não, sim, não, não, sim, não, não).
pokemon('Pinsir', não, sim, não, não, sim, não, não).
pokemon('Tauros' não, não, não, não, sim, não, não).
pokemon('Magikarp', sim, não, não, não, não, não, não).
pokemon('Gyarados', não, não, não, não, não, não, não).
pokemon('Lapras', não, não, não, não, sim, não, não).
pokemon('Ditto', não, não, não, não, não, não, não).
pokemon('Eevee', sim, não, não, não, sim, não, não).
pokemon('Vaporeon', não, não, não, não, sim, não, não).
pokemon('Jolteon', não, não, não, não, sim, não, não).
pokemon('Flareon', não, não, não, não, sim, não, não).
pokemon('Porygon', não, não, não, não, não, sim, não).
pokemon('Omanyte', sim, não, não, não, não, não, sim).
pokemon('Omastar', não, não, não, não, não, não, sim).
pokemon('Kabuto', sim, não, não, não, sim, não, sim).
pokemon('Kabutops', não, sim, não, não, sim, não, sim).
pokemon('Aerodactyl', , não, sim, não, não, sim, sim, sim).
pokemon('Snorlax', não, sim, não, não, sim, não, não).
pokemon('Articuno', não, sim, não, sim, sim, sim, não).
pokemon('Zapdos', não, sim, não, sim, sim, sim, não).
pokemon('Moltres', não, sim, não, sim, sim, sim, não).
pokemon('Dratini', sim, não, não, não, não, não, não).
pokemon('Dragonair', sim, não, não, não, não, não, não).
pokemon('Dragonite', não, sim, não, não, sim, sim, não).
pokemon('Mewtwo', não, sim, não, sim, sim, sim, não).
pokemon('Mew', não, sim, não, sim, sim, sim, não).